/**
 * Конфигурация полей профиля для разных ролей пользователей
 * Каждое поле содержит информацию о типе, заголовке, плейсхолдере и валидации
 */
export const roleFieldsConfig = {
    client: {
        name: {
            id: 'name',
            type: 'text',
            label: 'ФИО*',
            placeholder: 'Введите ФИО',
            validation: (value) => value.length >= 2,
            errorMessage: 'ФИО должно содержать не менее 2 символов',
            required: true,
            order: 1,
        },
        phone: {
            id: 'phone',
            type: 'phone',
            label: 'Номер телефона',
            placeholder: 'Введите номер телефона',
            validation: (value) => !value || /^\+?[0-9]{10,15}$/.test(value),
            errorMessage: 'Введите корректный номер телефона',
            required: false,
            order: 2,
        },
        gender: {
            id: 'gender',
            type: 'select',
            label: 'Пол',
            options: [
                { value: 'MALE', label: 'Мужской' },
                { value: 'FEMALE', label: 'Женский' },
                { value: 'OTHER', label: 'Другой' },
                { value: 'PREFER_NOT_TO_SAY', label: 'Предпочитаю не указывать' },
            ],
            required: false,
            order: 3,
        },
        address: {
            id: 'address',
            type: 'text',
            label: 'Адрес',
            placeholder: 'Введите адрес',
            validation: (value) => !value || value.length >= 5,
            errorMessage: 'Адрес должен содержать не менее 5 символов',
            required: false,
            order: 4,
        },
        districtId: {
            id: 'districtId',
            type: 'select',
            label: 'Район доставки',
            placeholder: 'Выберите район доставки',
            required: false,
            order: 5,
        }
    },

    supplier: {
        companyName: {
            id: 'companyName',
            type: 'text',
            label: 'Название компании',
            placeholder: 'Введите название компании',
            validation: (value) => value.length >= 2,
            errorMessage: 'Название компании должно содержать не менее 2 символов',
            required: true,
            order: 1,
        },
        contactPerson: {
            id: 'contactPerson',
            type: 'text',
            label: 'Контактное лицо',
            placeholder: 'Введите ФИО контактного лица',
            validation: (value) => value.length >= 2,
            errorMessage: 'ФИО контактного лица должно содержать не менее 2 символов',
            required: true,
            order: 2,
        },
        phone: {
            id: 'phone',
            type: 'phone',
            label: 'Номер телефона',
            placeholder: 'Введите номер телефона',
            validation: (value) => !value || /^\+?[0-9]{10,15}$/.test(value),
            errorMessage: 'Введите корректный номер телефона',
            required: false,
            order: 3,
        },
        address: {
            id: 'address',
            type: 'text',
            label: 'Юридический адрес',
            placeholder: 'Введите юридический адрес',
            validation: (value) => !value || value.length >= 5,
            errorMessage: 'Адрес должен содержать не менее 5 символов',
            required: false,
            order: 4,
        },
        inn: {
            id: 'inn',
            type: 'text',
            label: 'ИНН',
            placeholder: 'Введите ИНН',
            validation: (value) => !value || /^[0-9]{10,12}$/.test(value),
            errorMessage: 'ИНН должен содержать 10 или 12 цифр',
            required: false,
            keyboardType: 'numeric',
            order: 5,
        },
        ogrn: {
            id: 'ogrn',
            type: 'text',
            label: 'ОГРН',
            placeholder: 'Введите ОГРН',
            validation: (value) => !value || /^[0-9]{13,15}$/.test(value),
            errorMessage: 'ОГРН должен содержать 13 или 15 цифр',
            required: false,
            keyboardType: 'numeric',
            order: 6,
        },
        bankAccount: {
            id: 'bankAccount',
            type: 'text',
            label: 'Расчетный счет',
            placeholder: 'Введите расчетный счет',
            validation: (value) => !value || /^[0-9]{20}$/.test(value),
            errorMessage: 'Расчетный счет должен содержать 20 цифр',
            required: false,
            keyboardType: 'numeric',
            order: 7,
        },
        bik: {
            id: 'bik',
            type: 'text',
            label: 'БИК',
            placeholder: 'Введите БИК',
            validation: (value) => !value || /^[0-9]{9}$/.test(value),
            errorMessage: 'БИК должен содержать 9 цифр',
            required: false,
            keyboardType: 'numeric',
            order: 8,
        },
        gender: {
            id: 'gender',
            type: 'select',
            label: 'Пол',
            options: [
                { value: 'MALE', label: 'Мужской' },
                { value: 'FEMALE', label: 'Женский' },
                { value: 'OTHER', label: 'Другой' },
                { value: 'PREFER_NOT_TO_SAY', label: 'Предпочитаю не указывать' },
            ],
            required: false,
            order: 9,
        },
    },

    employee: {
        name: {
            id: 'name',
            type: 'text',
            label: 'ФИО*',
            placeholder: 'Введите ФИО сотрудника',
            validation: (value) => value.length >= 2,
            errorMessage: 'ФИО должно содержать не менее 2 символов',
            required: true,
            order: 1,
        },
        position: {
            id: 'position',
            type: 'text',
            label: 'Должность',
            placeholder: 'Введите должность',
            validation: (value) => !value || value.length >= 2,
            errorMessage: 'Должность должна содержать не менее 2 символов',
            required: false,
            order: 2,
        },
        phone: {
            id: 'phone',
            type: 'phone',
            label: 'Номер телефона',
            placeholder: 'Введите номер телефона',
            validation: (value) => !value || /^\+?[0-9]{10,15}$/.test(value),
            errorMessage: 'Введите корректный номер телефона',
            required: false,
            order: 3,
        },
        address: {
            id: 'address',
            type: 'text',
            label: 'Адрес',
            placeholder: 'Введите адрес',
            validation: (value) => !value || value.length >= 5,
            errorMessage: 'Адрес должен содержать не менее 5 символов',
            required: false,
            order: 4,
        },
        districts: {
            id: 'districts',
            type: 'multiselect',
            label: 'Районы работы',
            placeholder: 'Выберите районы работы',
            required: false,
            order: 5,
        },
        warehouseId: {
            id: 'warehouseId',
            type: 'select',
            label: 'Склад',
            placeholder: 'Выберите склад',
            required: false,
            order: 5.5,
        },
        gender: {
            id: 'gender',
            type: 'select',
            label: 'Пол',
            options: [
                { value: 'MALE', label: 'Мужской' },
                { value: 'FEMALE', label: 'Женский' },
                { value: 'OTHER', label: 'Другой' },
                { value: 'PREFER_NOT_TO_SAY', label: 'Предпочитаю не указывать' },
            ],
            required: false,
            order: 6,
        },
    },

    driver: {
        name: {
            id: 'name',
            type: 'text',
            label: 'ФИО*',
            placeholder: 'Введите ФИО водителя',
            validation: (value) => value.length >= 2,
            errorMessage: 'ФИО должно содержать не менее 2 символов',
            required: true,
            order: 1,
        },
        phone: {
            id: 'phone',
            type: 'phone',
            label: 'Номер телефона',
            placeholder: 'Введите номер телефона',
            validation: (value) => !value || /^\+?[0-9]{10,15}$/.test(value),
            errorMessage: 'Введите корректный номер телефона',
            required: false,
            order: 2,
        },
        address: {
            id: 'address',
            type: 'text',
            label: 'Адрес',
            placeholder: 'Введите адрес',
            validation: (value) => !value || value.length >= 5,
            errorMessage: 'Адрес должен содержать не менее 5 символов',
            required: false,
            order: 3,
        },
        districts: {
            id: 'districts',
            type: 'multiselect',
            label: 'Районы доставки',
            placeholder: 'Выберите районы доставки',
            required: false,
            order: 4,
        },
        gender: {
            id: 'gender',
            type: 'select',
            label: 'Пол',
            options: [
                { value: 'MALE', label: 'Мужской' },
                { value: 'FEMALE', label: 'Женский' },
                { value: 'OTHER', label: 'Другой' },
                { value: 'PREFER_NOT_TO_SAY', label: 'Предпочитаю не указывать' },
            ],
            required: false,
            order: 5,
        },
    },

    admin: {
        name: {
            id: 'name',
            type: 'text',
            label: 'ФИО*',
            placeholder: 'Введите ФИО администратора',
            validation: (value) => value.length >= 2,
            errorMessage: 'ФИО должно содержать не менее 2 символов',
            required: true,
            order: 1,
        },
        phone: {
            id: 'phone',
            type: 'phone',
            label: 'Номер телефона',
            placeholder: 'Введите номер телефона',
            validation: (value) => !value || /^\+?[0-9]{10,15}$/.test(value),
            errorMessage: 'Введите корректный номер телефона',
            required: false,
            order: 2,
        },
        address: {
            id: 'address',
            type: 'text',
            label: 'Адрес',
            placeholder: 'Введите адрес',
            validation: (value) => !value || value.length >= 5,
            errorMessage: 'Адрес должен содержать не менее 5 символов',
            required: false,
            order: 3,
        },
        gender: {
            id: 'gender',
            type: 'select',
            label: 'Пол',
            options: [
                { value: 'MALE', label: 'Мужской' },
                { value: 'FEMALE', label: 'Женский' },
                { value: 'OTHER', label: 'Другой' },
                { value: 'PREFER_NOT_TO_SAY', label: 'Предпочитаю не указывать' },
            ],
            required: false,
            order: 4,
        },
    },
};